### ISSUE TITLE
[Bugi] Laskutusliitännäisessä aikavälin rajaus ei toimi, kun haetaan laskutettuja niteitä

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/koha-plugin-overdue-tool#1]
### Mikä vikana?

Kun haetaan jo laskutettuja niteitä, aikaväli jolta ne halutaan, ei toimi. Näkyville tulee myös asiakkaan aiemmin laskutetut niteet, jotka eivät sisälly rajattuun aikaväliin.  
Esim. https://outi.koha-suomi.fi/cgi-bin/koha/members/moremember.pl?borrowernumber=189486

### Mitä pitäisi tapahtua

Kun hakee laskutetut tietyltä aikaväliltä, näkyville pitäisi tulla vain ne laskutetut niteet, jotka on laskutettu rajatulla aikavälillä.

### Kohan osio

Laskutus

**Comment by lmstrand** [comment]
Toisessa laskutustyökaluun liittyvässä tiketissä [https://github.com/KohaSuomi/koha-plugin-overdue-tool/issues/2](url) on raportti, jota voi käyttää myös sillä aikaa, kunnes ongelma ratkaistaan laskutustyökalussa.

**Comment by emta001** [comment]
> Jokin tuossa haussa näyttäisi tosiaan olevan hieman vinksallaan. Kun hain esimerkki asiakkaan laskua tällä asetuksella:
> 
> ![Screenshot 2022-10-21 at 15-09-53 Koha-Suomi - Laskutustyökalu](https://user-images.githubusercontent.com/37581745/197192660-7ce59164-a600-48ec-8f3c-474b93e72183.png)
> 
> Saan tulokseksi myös 23.3. vanhentuneen lainan:
> 
> ![Screenshot 2022-10-21 at 15-10-09 Koha-Suomi - Laskutustyökalu](https://user-images.githubusercontent.com/37581745/197192708-546fb3e6-60fc-4f22-a396-0b90b177a10e.png)
> 
> Mutta jos säädän aikavälin loppupäivämäärää 4.4., asiakasta ei löydy ollenkaan. Tutkaillaan jossain vaiheessa.

Tämä selvisi. Eli koodissa haetaan aikaväliä between operaattorilla, mutta koska päivämäärät ovat muodossa yyyy-mm-dd loppupäivässä käytetään automaattisesti kellonaikaa 00:00:00. Tällöin päivämäärä siis rajautuukin haun ulkopuolelle. Korjataan tämä samalla kun korjataan tuo ylimääräisten laskuettavien haku.

**Comment by piiaseme** [comment]
Mielestämme haku voi edelleen toimia lainojen eräpäivän mukaan, Me saadaan raportilla tieto laskutuspäivän mukaan, joten hyvä jos voimme tarvittaessa liitännäisessä tehdä haun lainojen eräpäivän mukaan.

**Comment by emta001** [comment]
Lisäsin pari korjausta testeille:

1) Päivämäärällä rajaaminen ei enää jätä huomiotta rajauksen päättymispäivää.
2) Listaukseen ei tule enää mukaan lainoja, jotka ovat rajauksen ulkopuolella.

**Comment by emta001** [comment]
Muokkasin otsikkoa, tämähän ei ole ongelma vain OUTIssa.
