### ISSUE TITLE
Laskutus-liitännäinen: Merkitse lähetetyt finvoice-laskut sent-tilaisiksi heti lähetyksen jälkeen

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/koha-plugin-overdue-tool#12]
### Mikä vikana?

Tällä hetkellä finvoice-laskut merkitään message_queque-tauluun sent-tilaisiksi vasta kun kaikki laskut on lähetetty eteenpäin. Tilanteessa, jossa osa laskuista on lähtenyt ja osa jäänyt lähettämättä jonkin virheen vuoksi tämä voi johtaa siihen, että jo lähetettyjä laskuja yritetään lähettää uudestaan.

Muutetaan toiminnallisuutta niin, että lasku merkitään lähetetyksi heti, kun se on lähetetty (eli kun se siirtyy palvelimella archived-hakemistoon).

**Comment by johannaraisa** [comment]
Voiko sulkea?

**Comment by emta001** [comment]
Voi, kukaan ei ole valitellut eikä mikään ole räjähtänyt :smile:
