### ISSUE TITLE
LOST-arvojen jättäminen laskutuksen ulkopuolelle

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/koha-plugin-overdue-tool#15]
### Kehitysehdotukseni

Kohan virkailijatyökalussa on mahdollisuus laittaa niteen kohdalle, että asiakas "Ilmoittaa palauttaneensa", joka ainakin Lumpeissa menee LOST-arvon tilaan. Tässä tilassa olevat niteet menevät laskutukseen, mikä aiheuttaa laskuttajille lisätyötä. Laskutustyökalussa ei tällä hetkellä ole mahdollista rajata tiettyjä LOST- ja NOT_LOAN -arvoja laskutuksen ulkopuolelle. 

Ehdottaisin, että laskutustyökaluun tehtäisiin muutos, jossa tiettyjä arvoja olisi mahdollista jättää laskutuksen ulkopuolella. Nämä arvot olisivat kimppakohtaisesti säädettävissä.

**Comment by johannaraisa** [comment]
Parannus on viety testeille, saa kokeilla.

**Comment by ajrajala** [comment]
Vaski-testillä testattu, nide katoaa laskutustyökalusta kun sille asettaa LOST-tilan ja päin vastoin.

**Comment by Hanna-Lumme** [comment]
Toimii myös Lumpeissa samalla tavoin kuin Vaskissa.

**Comment by pirliis** [comment]
OUTIssa toimii myös samalla tavalla kuin Vaskissa ja Lumpeessa.

**Comment by AnneliO** [comment]
Sellainen hoksautus varalta tänne (Pirlii hoksasi), että jos MarkLostItemsAsReturned-järjestelmäasetuksessa on määritetty nide palautumaan lainasta, kun se merkitään kadonneeksi, niin nide katoaa myös siinä tapauksessa laskutettavista. Eli kannattaa myös tarkistaa, mitä tuohon asetukseen on valittuna, jotta laskutettavien listalta poistuminen johtuu tosiaan LOST-arvosta eikä siitä, että se ei ole enää lainassa. :)

**Comment by ajrajala** [comment]
Vaskissa asetukseen ei ole määritelty nidettä palautumaan lainasta eli testitulos ok. 👍

**Comment by johannaraisa** [comment]
Tämä on viety jo tuotantoon 30.7., suljen tiketin
