### ISSUE TITLE
Laskutettujen niteiden määrän ja laskutetun aineiston yhteissumma ei aina täsmää

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/koha-plugin-overdue-tool#3]
### Mikä vikana?

Laskutettujen niteiden määrän ja laskutetun aineiston yhteissumma ei aina vastaa todellista lukua. Esimerkiksi OUTIssa aikavälillä 5.4.-16.4. laskujen määrän tuloksena on 19, mutta  niteiden määräksi tulee 8 ja yhteissummaksi 272,75 euroa. Todelliset määrät ovat  35 nidettä ja yhteisumma n. 1423,35 e

### Mitä pitäisi tapahtua

Laskutettujen niteiden määrän ja laskutetun aineiston yhteisumman tulisi vastata kaikilla aikaväleillä laskutettujen listauksessa esiintyvien niteiden määrää ja niiden korvaushintojen yhteissummaa.

**Comment by emta001** [comment]
Ongelmana on siis se, että listaus käyttää ns. laiskaa latausta eikä palauta kerralla kaikkea dataa näkymään. Kun selaimen konsolista katselee, niin kutsuja tehdään sellaiset 6 kappaletta ja niissä palautetaan aina x määrä tuloksia. Se mikä yhteisumma ja niteiden määrä palautetaan vaihtelee. Eli pitäisi keksiä kuinka yhteisummien tulokset palautetaan vasta sitten kun kaikki tulokset on palautettu.

**Comment by pknuuti** [comment]
Vaaran testillä on niin pieni otanta, että en ole varma onko se hyvä testikohde. Ainakin tulokset oli oikein eli näytti molempien laskujen laskutettujen niteiden määrän oikein samoin kuin yhteissumman. Yhteissummassa pieni kauneusvirhe eli siinä on piste erottimena pilkun sijaan, vaikka laskuissa summat ovat oikeassa muodossa.

**Comment by MikkoLiimatainen** [comment]
Vaskissakin kaikki luvut olivat oikein.

**Comment by pirliis** [comment]
Testailin myös OUTIssa. Pienillä otannoilla luvut näyttivät täsmäävän. Ajattelin, että testaisin vielä niin toisena päivänä, että teen yhden isomman finvoice-laskutuserän ja vertaan sitä raporttiin, jolla voi hakea laskutetut laskutuspäivän mukaan.

**Comment by emta001** [comment]
> Vaaran testillä on niin pieni otanta, että en ole varma onko se hyvä testikohde. Ainakin tulokset oli oikein eli näytti molempien laskujen laskutettujen niteiden määrän oikein samoin kuin yhteissumman. Yhteissummassa pieni kauneusvirhe eli siinä on piste erottimena pilkun sijaan, vaikka laskuissa summat ovat oikeassa muodossa.

Korjailen vielä tuon pilkkuvirheen viimeistään huomenna. Voisihan siihen summan perään vielä turssata että "euroa".

**Comment by emta001** [comment]
Pilkkuvirheet korjattu testeille.

**Comment by emta001** [comment]
Ominaisuus tuotu tuotantoon. Testasin OUTIssa aikavälillä 4.4.-16.4. ja vaikuttaisi sille, että ainakin niteiden yhteismäärä täsmää.
