### ISSUE TITLE
Laskutusliitännäisessä liian pitkään ArticleTitleen jää edelleen yksi ylimääräinen merkki

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/koha-plugin-overdue-tool#5]
### Mikä vikana?

Liitännäistä korjattiin niin, että tietueen nimeke katkaistaan, jos sen ja tekijän nimen yhteenlaskettu pituus on yli 100 merkkiä. Ainakin Vaskissa on kuitenkin syntynyt lasku, jossa yhteenlaskettu merkkimäärä on 101 ja lasku ei ole mennyt validoinnista läpi. Katkaisu ei siis toimi ihan kuten pitää.

**Comment by emta001** [comment]
Korjaus tuotu testeille.

**Comment by MikkoLiimatainen** [comment]
Kahdella testitietueella testattuna katkaisu näyttäisi toimivan nyt oikein. Sain raportilla yli sata merkkiä sisältävien tietuenimien laskuille articlename-kenttien char_length-pituudeksi sata merkkiä.

**Comment by emta001** [comment]
Korjaus tuotu tuotantoihin.
