### ISSUE TITLE
Helle-testi: laskutustyökalu-liitännäisessä ei pääse muodostamaan kirjastoryhmiä

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/koha-plugin-overdue-tool#6]
### Mikä vikana?

Helle-testin laskutustyökalu-liitännäisessä ei pääse muodostamaan kirjastoryhmiä, sillä ryhmään ei saa valittua kirjastoja.

Laskutusliitännäisen määrittely -toiminnossa on heti vastassa Tapahtui virhe -ilmoitus
![kuva](https://user-images.githubusercontent.com/99952449/215058811-f93971da-5318-4553-9526-3c6b8bd3814c.png)

Koha-polku:
Työkaluliitännäiset
 Laskutustyökalu
  Toiminnot 
   Määrittely

**Comment by emta001** [comment]
Plugari oli disabloitu. Enabloin sen ja käynnistin palvelut uudestaan. Nyt pitäisi toimia.

**Comment by Kati-Helle** [comment]
Toimii. Kiitos Emmi :)
