### ISSUE TITLE
Nimekkeen katkaisu laskutuksessa vain Finvoice-sanomille

### ISSUE THREAD

**Issue by johannaraisa** [KohaSuomi/koha-plugin-overdue-tool#7]
### Mikä vikana?

Tällä hetkellä laskua luodessa yli 100 merkin nimeke+tekijä yhdistelmästä katkaistaan nimekkeen ylimääräiset merkit, jotta ne mahtuvat 100 merkkimäärään sisään. Finvoice tarvitsee tämän, mutta muilta voidaan jättää tekemättä. Muutetaan niin, että tehdään vain Finvoice-sanomien arvoille.

**Comment by johannaraisa** [comment]
Siirretty Finvoice.pm moduuliin, testattava kun luodaan finvoicen xml-tiedostot.

**Comment by piiaseme** [comment]
Miten tätä on tarkoitus testata? :)
Tuotannossa vai testillä?

**Comment by johannaraisa** [comment]
Jos voisit luoda testiin Finvoicen, missä on pitkä tekijä+nimeke, yli 100 merkkiä. Pitäisi siinä PDF-jäljenteessä näkyä kokonaan ja sitten kokeilen ajaa sen finvoice-sanoman ja tarkastelen onko siihen katkennut 100 merkkiin.

**Comment by piiaseme** [comment]
OUTI-testillä asiakkaalla lainassa nyt 2 nidettä. Toinen on yli 100 merkkinen (tietue+tekijä). Toinen laina ei ehkä ole niin pitkä, mutta pitkä kuitenkin. 

Luon laskun sitten, kun testille on tuotu tuotannosta määrittelyt.

borrowernumber=248137

**Comment by piiaseme** [comment]
Lasku luotu 11.1.2024 testillä Oulun Finvoicella.

Borrower: 248137 Narja Vesikota
Lainojen eräpäivä 1.1.2023

Toivottavasti merkkejä on tarpeeksi:
![kuva](https://github.com/KohaSuomi/koha-plugin-overdue-tool/assets/98805552/3441d0f3-50b3-4ae6-9df1-2022a0197068)
