### ISSUE TITLE
Laskutusliitännäinen: poistetaan ominaisuudet Lisää hinta asiakkaan maksuihin ja Lisää myöhästymismaksut laskuun

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/koha-plugin-overdue-tool#8]
### Mikä vikana?

Taulussa "accountlines" ei ole enää saraketta "accounttype", vaan se on korvattu sarakkeilla "credit_type_code" ja "debit_type_code". Liitännäiseen pitää tehdä muutos tämän osalta.

**Comment by johannaraisa** [comment]
Voiko sulkea?

**Comment by emta001** [comment]
Ei voi, tätä ei oo vielä tehty. En muista miksi jäi kesken, saatto liittyä siihen etten tiennyt mikä vastais "FU" tyyppistä maksu tjsp.

**Comment by johannaraisa** [comment]
Olis siitä varmaan joku jo valittanut, ku puuttuu koko sarake tietokannasta. En usko, että antaa tallentaa. :smiley:

**Comment by emta001** [comment]
> Kukaan ei taida edes käyttää noita ominaisuuksia, olikohan meillä suunnitelmissa että poistetaan koko ominaisuus?

Ei voi muistaa enää :smile: Mutta kyllä sen voinee pudottaa, olishan tää homma jo kopsahtanut ajat sitten jos tuo olis ongelma. Tais olla lähinnä niin, että mun testiympäristössä se rupes jostain syystä kaatuilemaan tuohon.

**Comment by johannaraisa** [comment]
No minäpä väsään tähän korjauksen

**Comment by johannaraisa** [comment]
Nyt on koodinpätkät poistettu ja kokeilin itse, ettei mikään räjähdä. :smile:

**Comment by johannaraisa** [comment]
Saa muutkin käydä kokeilemassa.

**Comment by johannaraisa** [comment]
Testaussuunnitelma on lähinnä kokeilee, että laskutus vielä toimii.

**Comment by ajrajala** [comment]
Testasin työkalua vaski-testillä, työkalun rajaukset näyttää pelittävän ja laskun muodostaminen lisää rajoitteen asiakkalle (+huoltajalle, jos kyseessä lapsi), korvaushintaa pystyy muokkaamaan ja tulostamaan laskujäljenteen. En nyt siis huomaa mitään räjähtäneen. :D

**Comment by johannaraisa** [comment]
Tää on jo tuotannossa, joten suljen.
