### ISSUE TITLE
Laskutustyökaluun ilmoitus nollasummasta

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/koha-plugin-overdue-tool#9]
### Kehitysehdotukseni

Esittäisin kehitysehdotuksena Laskutustyökaluun jonkinlaista ilmoitusta siitä, kun asiakkaalla on laskutettavana aineistoa, jonka korvaushinta on 0€. 0€ maksut eivät päädy automaattisesti laskulle ja tällä hetkellä laskutustyötä tekevät eivät välttämättä hoksaa avata asiakkaan tietoja ja katsoa tarkemmin mitä korvattavaa on menossa asiakkaalle. Osalle saman tietueen niteistä on myös saatettu merkitä korvaushinta, osalta se on taas jääny puuttumaan.

Tämän ilmoituksen tarkoituksena olisi kiinnittää laskutustyötä tekevän huomio siihen, että asiakkaalla on myöhässä/korvauksessa aineistoa, jonka maksu on 0€. Näin työntekijä pystyisi tarvittaessa korjaamaan summan oikeaksi.

**Comment by AnneliO** [comment]
Pääkäyttäjäpalaverissa keskusteltiin tästä aiheesta ja suurin osa oli sitä mieltä, että tällaista muutosta ei tarvita, koska laskuttajan tehtävänä on oletusarvoisesti käydä kaikki laskutettavat niteet läpi ja korjata puutteelliset rivit. :)
